In [ ]:
Name : Omkar Hulawale
Class , Batch : TE-A , A3 Batch
Roll No: 13165

In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv(r"C:\Users\hulaw\OneDrive\Desktop\DSBDA\data.csv")
df

    Unnamed: 0         A         B         C         D
0            0 -1.557181  0.373416  1.040685 -0.648513
1            1 -0.835872 -0.005259  0.502099 -0.956839
2            2 -0.257153  2.638228 -0.535731 -1.069443
3            3 -0.505502 -0.339260  0.602622 -1.420995
4            4  1.366398 -0.368296  0.642091  1.609680
5            5 -1.350101  0.210097 -0.743280  0.035729
6            6 -0.621305 -0.620733  0.141429 -1.831875
7            7 -0.670370 -0.379230  1.950228 -0.487202
8            8 -1.360577  0.044675 -0.576289  0.998686
9            9 -0.120302 -0.146491 -0.420956  1.412786
10          10  0.216936  0.398267  0.342519  0.387263
11          11  0.567832 -2.023668 -0.315318 -0.064349
12          12 -0.161148 -0.118924 -1.226679 -0.932540
13          13 -1.063620  0.041304 -1.037695  0.628520
14          14  0.912931  0.848745 -1.215276 -0.024202
15          15 -0.661489 -1.543994 -0.452754 -1.589521
16          16 -0.272063 -1.012084  0.414147 -0.021171
17          17  0.468146  0.232378 -1.890289  0.827622
18          18  1.744694  0.052282  0.890462 -0.155540
19          19  0.381029  0.666666  0.957832  1.476093
20          20  0.503970  0.567258  1.578919  1.041839
21          21 -0.561937  0.534243  0.246232  0.763021
22          22  0.064446 -0.483406 -0.584869 -1.066767
23          23  2.762885  0.060047 -0.709070 -1.350154
24          24 -0.399912  0.755714 -0.138098  0.771859
25          25  2.289132 -0.178023  0.392030 -1.638884
26          26 -1.667799 -0.723245 -0.298492 -0.464406
27          27  0.871473 -0.875910  1.693428 -0.120278
28          28  2.035892 -0.442804  1.710999 -0.164896
29          29  2.646331  0.006441 -0.819143 -0.140657
30          30 -1.645022  1.841754 -0.390258 -0.118842
31          31 -2.085251  0.043444 -0.183578  0.548298
32          32  1.427635 -0.349981  1.038814 -0.955178
33          33 -0.680210  0.566180 -0.325638  0.244383
34          34 -0.026502  0.758021  0.466427 -0.198146
35          35  0.433309  0.623019 -0.201789  1.983037
36          36  0.646673 -0.715421 -0.322057  0.645001
37          37  0.048681 -1.203145  0.460026  0.192644
38          38  0.098718 -0.672915 -0.229832 -0.187133
39          39 -0.059930 -1.472300 -1.281250 -0.666214
40          40  1.515724  0.207993 -1.037067 -0.393363
41          41 -0.949868 -1.115604 -0.554789  1.324991
42          42 -1.452316 -0.572414 -0.808790  1.615190
43          43 -1.117542  0.083952 -0.874761  0.884389
44          44  0.834118  0.423509 -0.565575 -0.169843
45          45 -0.382312  0.175994 -0.820539 -0.542783
46          46 -0.982393 -0.396464  0.550612  1.584936
47          47  0.581846 -0.994098  0.519327  1.286765
48          48 -0.412282 -1.889874 -0.047348 -0.767669
49          49  0.446292  0.326242  0.230500  0.841655

In [7]:
df.isnull()

    Unnamed: 0      A      B      C      D
0        False  False  False  False  False
1        False  False  False  False  False
2        False  False  False  False  False
3        False  False  False  False  False
4        False  False  False  False  False
5        False  False  False  False  False
6        False  False  False  False  False
7        False  False  False  False  False
8        False  False  False  False  False
9        False  False  False  False  False
10       False  False  False  False  False
11       False  False  False  False  False
12       False  False  False  False  False
13       False  False  False  False  False
14       False  False  False  False  False
15       False  False  False  False  False
16       False  False  False  False  False
17       False  False  False  False  False
18       False  False  False  False  False
19       False  False  False  False  False
20       False  False  False  False  False
21       False  False  False  False  False
22       False  False  False  False  False
23       False  False  False  False  False
24       False  False  False  False  False
25       False  False  False  False  False
26       False  False  False  False  False
27       False  False  False  False  False
28       False  False  False  False  False
29       False  False  False  False  False
30       False  False  False  False  False
31       False  False  False  False  False
32       False  False  False  False  False
33       False  False  False  False  False
34       False  False  False  False  False
35       False  False  False  False  False
36       False  False  False  False  False
37       False  False  False  False  False
38       False  False  False  False  False
39       False  False  False  False  False
40       False  False  False  False  False
41       False  False  False  False  False
42       False  False  False  False  False
43       False  False  False  False  False
44       False  False  False  False  False
45       False  False  False  False  False
46       False  False  False  False  False
47       False  False  False  False  False
48       False  False  False  False  False
49       False  False  False  False  False

In [9]:
df.notnull()

    Unnamed: 0     A     B     C     D
0         True  True  True  True  True
1         True  True  True  True  True
2         True  True  True  True  True
3         True  True  True  True  True
4         True  True  True  True  True
5         True  True  True  True  True
6         True  True  True  True  True
7         True  True  True  True  True
8         True  True  True  True  True
9         True  True  True  True  True
10        True  True  True  True  True
11        True  True  True  True  True
12        True  True  True  True  True
13        True  True  True  True  True
14        True  True  True  True  True
15        True  True  True  True  True
16        True  True  True  True  True
17        True  True  True  True  True
18        True  True  True  True  True
19        True  True  True  True  True
20        True  True  True  True  True
21        True  True  True  True  True
22        True  True  True  True  True
23        True  True  True  True  True
24        True  True  True  True  True
25        True  True  True  True  True
26        True  True  True  True  True
27        True  True  True  True  True
28        True  True  True  True  True
29        True  True  True  True  True
30        True  True  True  True  True
31        True  True  True  True  True
32        True  True  True  True  True
33        True  True  True  True  True
34        True  True  True  True  True
35        True  True  True  True  True
36        True  True  True  True  True
37        True  True  True  True  True
38        True  True  True  True  True
39        True  True  True  True  True
40        True  True  True  True  True
41        True  True  True  True  True
42        True  True  True  True  True
43        True  True  True  True  True
44        True  True  True  True  True
45        True  True  True  True  True
46        True  True  True  True  True
47        True  True  True  True  True
48        True  True  True  True  True
49        True  True  True  True  True

In [11]:
df.isnull().sum()

Unnamed: 0    0
A             0
B             0
C             0
D             0
dtype: int64

In [13]:
df.notnull().sum()

Unnamed: 0    50
A             50
B             50
C             50
D             50
dtype: int64

In [15]:
df.describe()

       Unnamed: 0          A          B          C          D
count    50.00000  50.000000  50.000000  50.000000  50.000000
mean     24.50000   0.020103  -0.123273  -0.044716   0.059140
std      14.57738   1.139660   0.845836   0.848863   0.966854
min       0.00000  -2.085251  -2.023668  -1.890289  -1.831875
25%      12.25000  -0.677750  -0.608653  -0.582724  -0.622080
50%      24.50000  -0.090116   0.000591  -0.215810  -0.091596
75%      36.75000   0.578342   0.361622   0.493181   0.813681
max      49.00000   2.762885   2.638228   1.950228   1.983037

In [17]:
df.size

250

In [19]:
df.ndim

2

In [21]:
df.shape

(50, 5)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50 non-null     int64
 1   A           50 non-null     float64
 2   B           50 non-null     float64
 3   C           50 non-null     float64
 4   D           50 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 2.1 KB

In [25]:
df["A"].astype(int)

0    -1
1     0
2     0
3     0
4     1
5    -1
6     0
7     0
8    -1
9     0
10    0
11    0
12    0
13   -1
14    0
15    0
16    0
17    0
18    1
19    0
20    0
21    0
22    0
23    2
24    0
25    2
26   -1
27    0
28    2
29    2
30   -1
31   -2
32    1
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    1
41    0
42   -1
43   -1
44    0
45    0
46    0
47    0
48    0
49    0
Name: A, dtype: int32

In [27]:
df.dropna()

    Unnamed: 0         A         B         C         D
0            0 -1.557181  0.373416  1.040685 -0.648513
1            1 -0.835872 -0.005259  0.502099 -0.956839
2            2 -0.257153  2.638228 -0.535731 -1.069443
3            3 -0.505502 -0.339260  0.602622 -1.420995
4            4  1.366398 -0.368296  0.642091  1.609680
5            5 -1.350101  0.210097 -0.743280  0.035729
6            6 -0.621305 -0.620733  0.141429 -1.831875
7            7 -0.670370 -0.379230  1.950228 -0.487202
8            8 -1.360577  0.044675 -0.576289  0.998686
9            9 -0.120302 -0.146491 -0.420956  1.412786
10          10  0.216936  0.398267  0.342519  0.387263
11          11  0.567832 -2.023668 -0.315318 -0.064349
12          12 -0.161148 -0.118924 -1.226679 -0.932540
13          13 -1.063620  0.041304 -1.037695  0.628520
14          14  0.912931  0.848745 -1.215276 -0.024202
15          15 -0.661489 -1.543994 -0.452754 -1.589521
16          16 -0.272063 -1.012084  0.414147 -0.021171
17          17  0.468146  0.232378 -1.890289  0.827622
18          18  1.744694  0.052282  0.890462 -0.155540
19          19  0.381029  0.666666  0.957832  1.476093
20          20  0.503970  0.567258  1.578919  1.041839
21          21 -0.561937  0.534243  0.246232  0.763021
22          22  0.064446 -0.483406 -0.584869 -1.066767
23          23  2.762885  0.060047 -0.709070 -1.350154
24          24 -0.399912  0.755714 -0.138098  0.771859
25          25  2.289132 -0.178023  0.392030 -1.638884
26          26 -1.667799 -0.723245 -0.298492 -0.464406
27          27  0.871473 -0.875910  1.693428 -0.120278
28          28  2.035892 -0.442804  1.710999 -0.164896
29          29  2.646331  0.006441 -0.819143 -0.140657
30          30 -1.645022  1.841754 -0.390258 -0.118842
31          31 -2.085251  0.043444 -0.183578  0.548298
32          32  1.427635 -0.349981  1.038814 -0.955178
33          33 -0.680210  0.566180 -0.325638  0.244383
34          34 -0.026502  0.758021  0.466427 -0.198146
35          35  0.433309  0.623019 -0.201789  1.983037
36          36  0.646673 -0.715421 -0.322057  0.645001
37          37  0.048681 -1.203145  0.460026  0.192644
38          38  0.098718 -0.672915 -0.229832 -0.187133
39          39 -0.059930 -1.472300 -1.281250 -0.666214
40          40  1.515724  0.207993 -1.037067 -0.393363
41          41 -0.949868 -1.115604 -0.554789  1.324991
42          42 -1.452316 -0.572414 -0.808790  1.615190
43          43 -1.117542  0.083952 -0.874761  0.884389
44          44  0.834118  0.423509 -0.565575 -0.169843
45          45 -0.382312  0.175994 -0.820539 -0.542783
46          46 -0.982393 -0.396464  0.550612  1.584936
47          47  0.581846 -0.994098  0.519327  1.286765
48          48 -0.412282 -1.889874 -0.047348 -0.767669
49          49  0.446292  0.326242  0.230500  0.841655

In [29]:
df["A"].astype(float)

0    -1.557181
1    -0.835872
2    -0.257153
3    -0.505502
4     1.366398
5    -1.350101
6    -0.621305
7    -0.670370
8    -1.360577
9    -0.120302
10    0.216936
11    0.567832
12   -0.161148
13   -1.063620
14    0.912931
15   -0.661489
16   -0.272063
17    0.468146
18    1.744694
19    0.381029
20    0.503970
21   -0.561937
22    0.064446
23    2.762885
24   -0.399912
25    2.289132
26   -1.667799
27    0.871473
28    2.035892
29    2.646331
30   -1.645022
31   -2.085251
32    1.427635
33   -0.680210
34   -0.026502
35    0.433309
36    0.646673
37    0.048681
38    0.098718
39   -0.059930
40    1.515724
41   -0.949868
42   -1.452316
43   -1.117542
44    0.834118
45   -0.382312
46   -0.982393
47    0.581846
48   -0.412282
49    0.446292
Name: A, dtype: float64

In [31]:
df

    Unnamed: 0         A         B         C         D
0            0 -1.557181  0.373416  1.040685 -0.648513
1            1 -0.835872 -0.005259  0.502099 -0.956839
2            2 -0.257153  2.638228 -0.535731 -1.069443
3            3 -0.505502 -0.339260  0.602622 -1.420995
4            4  1.366398 -0.368296  0.642091  1.609680
5            5 -1.350101  0.210097 -0.743280  0.035729
6            6 -0.621305 -0.620733  0.141429 -1.831875
7            7 -0.670370 -0.379230  1.950228 -0.487202
8            8 -1.360577  0.044675 -0.576289  0.998686
9            9 -0.120302 -0.146491 -0.420956  1.412786
10          10  0.216936  0.398267  0.342519  0.387263
11          11  0.567832 -2.023668 -0.315318 -0.064349
12          12 -0.161148 -0.118924 -1.226679 -0.932540
13          13 -1.063620  0.041304 -1.037695  0.628520
14          14  0.912931  0.848745 -1.215276 -0.024202
15          15 -0.661489 -1.543994 -0.452754 -1.589521
16          16 -0.272063 -1.012084  0.414147 -0.021171
17          17  0.468146  0.232378 -1.890289  0.827622
18          18  1.744694  0.052282  0.890462 -0.155540
19          19  0.381029  0.666666  0.957832  1.476093
20          20  0.503970  0.567258  1.578919  1.041839
21          21 -0.561937  0.534243  0.246232  0.763021
22          22  0.064446 -0.483406 -0.584869 -1.066767
23          23  2.762885  0.060047 -0.709070 -1.350154
24          24 -0.399912  0.755714 -0.138098  0.771859
25          25  2.289132 -0.178023  0.392030 -1.638884
26          26 -1.667799 -0.723245 -0.298492 -0.464406
27          27  0.871473 -0.875910  1.693428 -0.120278
28          28  2.035892 -0.442804  1.710999 -0.164896
29          29  2.646331  0.006441 -0.819143 -0.140657
30          30 -1.645022  1.841754 -0.390258 -0.118842
31          31 -2.085251  0.043444 -0.183578  0.548298
32          32  1.427635 -0.349981  1.038814 -0.955178
33          33 -0.680210  0.566180 -0.325638  0.244383
34          34 -0.026502  0.758021  0.466427 -0.198146
35          35  0.433309  0.623019 -0.201789  1.983037
36          36  0.646673 -0.715421 -0.322057  0.645001
37          37  0.048681 -1.203145  0.460026  0.192644
38          38  0.098718 -0.672915 -0.229832 -0.187133
39          39 -0.059930 -1.472300 -1.281250 -0.666214
40          40  1.515724  0.207993 -1.037067 -0.393363
41          41 -0.949868 -1.115604 -0.554789  1.324991
42          42 -1.452316 -0.572414 -0.808790  1.615190
43          43 -1.117542  0.083952 -0.874761  0.884389
44          44  0.834118  0.423509 -0.565575 -0.169843
45          45 -0.382312  0.175994 -0.820539 -0.542783
46          46 -0.982393 -0.396464  0.550612  1.584936
47          47  0.581846 -0.994098  0.519327  1.286765
48          48 -0.412282 -1.889874 -0.047348 -0.767669
49          49  0.446292  0.326242  0.230500  0.841655

In [33]:
df.head(6)

   Unnamed: 0         A         B         C         D
0           0 -1.557181  0.373416  1.040685 -0.648513
1           1 -0.835872 -0.005259  0.502099 -0.956839
2           2 -0.257153  2.638228 -0.535731 -1.069443
3           3 -0.505502 -0.339260  0.602622 -1.420995
4           4  1.366398 -0.368296  0.642091  1.609680
5           5 -1.350101  0.210097 -0.743280  0.035729

In [35]:
df.tail(5)

    Unnamed: 0         A         B         C         D
45          45 -0.382312  0.175994 -0.820539 -0.542783
46          46 -0.982393 -0.396464  0.550612  1.584936
47          47  0.581846 -0.994098  0.519327  1.286765
48          48 -0.412282 -1.889874 -0.047348 -0.767669
49          49  0.446292  0.326242  0.230500  0.841655

In [37]:
df.shape

(50, 5)

In [39]:
df.mean()

Unnamed: 0    24.500000
A              0.020103
B             -0.123273
C             -0.044716
D              0.059140
dtype: float64

In [41]:
df.median()

Unnamed: 0    24.500000
A             -0.090116
B              0.000591
C             -0.215810
D             -0.091596
dtype: float64

In [47]:
df['A'].head(5).mode()

0   -1.557181
1   -0.835872
2   -0.505502
3   -0.257153
4    1.366398
Name: A, dtype: float64